version: "3.9"
services:
   frontend:
      build: src/frontend
      depends_on:
         db:
            condition: service_started
         broker:
            condition: service_started
      extra_hosts:
         - "host.docker.internal:host-gateway"
      ports:
         - "80:3000"
   backend:
      build: src/backend
      network_mode: host
      volumes:
         - "./src/backend/updates:/app/updates:ro"
      depends_on:
         db:
            condition: service_started
         broker:
            condition: service_started
      environment:
         - SECRET_KEY=yuriAuthKey
      env_file:
         - "src/backend/.env"
   db:
      build: src/db
      volumes:
         - "./data/db:/var/lib/mysql"
      ports:
         - "3306:3306"
   broker:
      image: eclipse-mosquitto
      ports:
         - "1883:1883"
      volumes:
         - "./src/broker/mosquitto.conf:/mosquitto/config/mosquitto.conf"
         - "./src/broker/password_file:/mosquitto/password_file"
         - "./data/broker/log:/mosquitto/log"
         - "./data/broker/data:/mosquitto/data"
   explorer:
      image: smeagolworms4/mqtt-explorer
      depends_on:
         broker:
            condition: service_started
      ports:
         - "127.0.0.1:4000:4000"
      volumes:
         - "./src/broker/explorer:/mqtt-explorer/config"
